"use strict";(()=>{var e={};e.id=7204,e.ids=[7204],e.modules={72934:e=>{e.exports=require("next/dist/client/components/action-async-storage.external.js")},54580:e=>{e.exports=require("next/dist/client/components/request-async-storage.external.js")},45869:e=>{e.exports=require("next/dist/client/components/static-generation-async-storage.external.js")},20399:e=>{e.exports=require("next/dist/compiled/next-server/app-page.runtime.prod.js")},30517:e=>{e.exports=require("next/dist/compiled/next-server/app-route.runtime.prod.js")},6113:e=>{e.exports=require("crypto")},6005:e=>{e.exports=require("node:crypto")},63976:(e,t,r)=>{r.r(t),r.d(t,{originalPathname:()=>y,patchFetch:()=>I,requestAsyncStorage:()=>l,routeModule:()=>m,serverHooks:()=>g,staticGenerationAsyncStorage:()=>x});var n={};r.r(n),r.d(n,{GET:()=>u,dynamic:()=>c});var a=r(49303),o=r(88716),s=r(60670),i=r(87070),p=r(81584),d=r(85662);let c="force-dynamic";async function u(e){try{let{userId:t}=await (0,p.I)();if(!t)return i.NextResponse.json({error:"Unauthorized"},{status:401});let r=e.nextUrl.searchParams,n=r.get("format")||"csv",a=r.get("range")||"7d",o=new Date,s=new Date(o.getTime()-864e5*("1d"===a?1:"7d"===a?7:"30d"===a?30:90)),{data:c}=await d.O.from("generations").select("*").gte("created_at",s.toISOString()).order("created_at",{ascending:!1}),{data:u}=await d.O.from("payments").select("*").gte("created_at",s.toISOString()).order("created_at",{ascending:!1});if("csv"===n){let e=["Type,User ID,Style,Status,Created At,URL/Details",...(c||[]).map(e=>["Generation",e.user_id,e.style,e.image_url?"Success":"Failed",e.created_at,e.image_url||"N/A"].join(",")),...(u||[]).map(e=>["Payment",e.user_id,e.payment_method,e.status,e.created_at,e.amount+" "+e.currency].join(","))].join("\n");return new i.NextResponse(e,{headers:{"Content-Type":"text/csv","Content-Disposition":`attachment; filename="nexora-logs-${a}-${Date.now()}.csv"`}})}{let e=`
Nexora Logs Report
Date Range: ${a}
Generated: ${new Date().toISOString()}

Generations: ${c?.length||0}
Payments: ${u?.length||0}

[PDF content would be generated here using a library like pdfkit or jsPDF]
      `.trim();return new i.NextResponse(e,{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="nexora-logs-${a}-${Date.now()}.pdf"`}})}}catch(e){return console.error("Export error:",e),i.NextResponse.json({error:"Internal server error"},{status:500})}}let m=new a.AppRouteRouteModule({definition:{kind:o.x.APP_ROUTE,page:"/api/admin/export/route",pathname:"/api/admin/export",filename:"route",bundlePath:"app/api/admin/export/route"},resolvedPagePath:"C:\\estudio-nexora-comet\\app\\api\\admin\\export\\route.ts",nextConfigOutput:"",userland:n}),{requestAsyncStorage:l,staticGenerationAsyncStorage:x,serverHooks:g}=m,y="/api/admin/export/route";function I(){return(0,s.patchFetch)({serverHooks:g,staticGenerationAsyncStorage:x})}},85662:(e,t,r)=>{r.d(t,{O:()=>n});let n=(0,r(76429).eI)("https://mdngrazjggsunpvtwbam.supabase.co","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kbmdyYXpqZ2dzdW5wdnR3YmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NjMyMDQsImV4cCI6MjA3ODEzOTIwNH0.EZD2ujsGnwUtz8rafZHOe8vDMOdoOcNYx8kBClqQxWs")}};var t=require("../../../../webpack-runtime.js");t.C(e);var r=e=>t(t.s=e),n=t.X(0,[2510,1584,6628],()=>r(63976));module.exports=n})();